<div class="container">
    <?php
        session_start();

        if(isset($_SESSION['emailpatient'])) {
    ?>
        <a href="/patient/logout" class="btn btn-secondary">Sair</a>
    <?php
        } else {
    ?>
        <a href="/patient/login" class="btn btn-primary">Entrar</a>
        <a href="/patient/register" class="btn btn-primary">Cadastrar-se</a>
    <?php
        }
    ?>

    <nav>
        <div>
            <a href="/">Início</a>
            <a href="/patient/request">Solicitar Consulta</a>
        </div>
    </nav>

    <h1>Agende Já</h1>


</div>