<div class="container">
    <h1 class="display-3 text-center">Solicitar Consulta</h1>

    <div class="display-6 text-center">
        <?=
            //strftime('%A', date('l', strtotime($this->view->day))) 
            strftime('%A, %d de %B de %Y', strtotime($this->view->day));
        ?>
    </div>

    <?php
        $startTime = $this->view->day . " 08:00";
        $scheduleCurrent = date("Y-m-d G:i");
        //getdate()['hours'] . ":0" . getdate()['minutes']
    ?>    

    <label for="Clinics">Clínica</label>
    <select name="id_medclinic" id="Clinics">
        <?php foreach($this->view->clinics as $key => $clinic) { ?>
        <option value="<?= $clinic['id_medclinic'] ?>"><?= $clinic['name'] ?></option>
        <?php } ?>
    </select>

    <table class="table  table-striped">
    <thead>
        <tr>
            <th scope="col">Horários</th>
            <th scope="col">Detalhes</th>
            <th scope="col">Ação</th>
        </tr>
    </thead>
    <tbody>
        <?php 
            $cont = 0;
            $qtd = count($this->view->requests);
            for($i = 0; $i < 15; $i++) { 
        ?>
            <tr>
                <th scope="row">
                    <?= date('H:i', strtotime($startTime)) ?>
                </th>
                <th scope="row">
                    <?php 
                        if( date('H:i', strtotime($this->view->requests[$cont]['date'])) == date('H:i', strtotime($startTime)) ) {
                            echo "Horário ocupado";
                            $cont += 1;
                        } else {
                            echo "******************"; 
                        }
                        
                    ?>
                </th>
                <td>
                    <button class="btn btn-primary" onclick="Click('<?= $this->view->day . ' ' . date('H:i', strtotime($startTime)) ?>')">Solicitar Consulta</button>
                </td>
            </tr>
        <?php
            $startTime = date('Y-m-d H:i', strtotime('+40 minutes', strtotime($startTime)));
            } 
        ?>
    </tbody>
    </table>
</div>

<?php
    echo "<pre>";
    print_r($this->view->requests);
    echo "</pre>";
    print_r(getdate());
    echo "<hr>";
    echo date('H:i', strtotime($scheduleCurrent));
    echo "<hr>";
    echo date('H:i', strtotime($this->view->requests[0]['date']));
    echo "<hr>";
    echo count($this->view->requests);
?>

<script>
    function Click(schedule) {
        var clinic = document.getElementById("Clinics").value;
        
        window.location.replace("/patient/schedule?id_medclinic=" + clinic + "&schedule=" + schedule);
    }
</script>