<div class="container">


    <?php
        if(isset($_GET)) {
            if(isset($_GET['success']) && $_GET['success'] == 'true') {
    ?>
                <div class="alert alert-success alert-dismissible fade show" role="alert">
                    Consulta solicitada com sucesso!
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
    <?php
        }}
    ?>


    <h1 class="display-3 text-center">Solicitar Consulta</h1>

    <div class="display-6 text-center">
        <?=
            //strftime('%A', date('l', strtotime($this->view->day))) 
            strftime('%A, %d de %B de %Y', strtotime($this->view->day));
        ?>
    </div>

    <?php
        $startTime = $this->view->day . " 08:00";
        $scheduleCurrent = date("Y-m-d G:i");
        //getdate()['hours'] . ":0" . getdate()['minutes']
    ?>    

    <label for="Clinics">Clínica</label>
    <select name="id_medclinic" id="Clinics">
        <?php foreach($this->view->clinics as $key => $clinic) { ?>
        <option value="<?= $clinic['id_medclinic'] ?>"><?= $clinic['name'] ?></option>
        <?php } ?>
    </select>

    <table class="table  table-striped">
    <thead>
        <tr>
            <th scope="col">Horários</th>
            <th scope="col">Detalhes</th>
            <th scope="col">Ação</th>
        </tr>
    </thead>
    <tbody>
        <?php 
            if($this->view->requests != NULL) {
                $qtd = count($this->view->requests);
            } else {
                $qtd = NULL;
            }
            $count = 0;
            for($i = 0; $i < 16; $i++) { 
                
        ?>
            <tr>
                <th scope="row">
                    <?= date('H:i', strtotime($startTime)) ?>
                </th>
                <th scope="row">
                    <?php
                        if($this->view->requests != NULL) {
                            if( $qtd != NULL && $count < $qtd && date('H:i', strtotime($this->view->requests[$count]['date'])) == date('H:i', strtotime($startTime)) ) {
                                echo "Horário ocupado!";
                                $count += 1;
                            } else {
                                echo "******************";
                            }
                        } else {
                            echo "******************";
                        }
                        
                    ?>
                </th>
                <td>
                    <?php
                        if( date('Y-m-d H:i', strtotime($startTime)) < date('Y-m-d H:i', strtotime('+40 minutes', strtotime($scheduleCurrent))) ) {
                            echo "Horário esgotado";
                        } 
                        else if($this->view->requests != NULL) {
                            if( $qtd != NULL && ($count - 1) < $qtd && date('H:i', strtotime($this->view->requests[$count-1]['date'])) == date('H:i', strtotime($startTime)) ) {
                                if($_SESSION['id_patient'] == $this->view->requests[$count-1]['id_patient']) {
                    ?>
                                    <button  class="btn btn-warning">Cancelar Consulta</button>
                    <?php
                                } else {
                                    echo "Horário ocupado! ";
                                }
                            } else {
                    ?>            <button class="btn btn-primary" onclick="Click('<?= $this->view->day . ' ' . date('H:i', strtotime($startTime)) ?>')">Solicitar Consulta</button>
                    <?php
                            }
                        } else if($this->view->requests == NULL && $qtd == NULL) {

                    ?>
                    <button class="btn btn-primary" onclick="Click('<?= $this->view->day . ' ' . date('H:i', strtotime($startTime)) ?>')">Solicitar Consulta</button>
                    <?php } ?>
                </td>
            </tr>
        <?php
            $startTime = date('Y-m-d H:i', strtotime('+40 minutes', strtotime($startTime)));
            } 
        ?>
    </tbody>
    </table>
</div>

<div class="container">
    <h1 class="display-6 text-center">Consultas Marcadas para essa data:</h1>
    <div class="row row-cols-1 row-cols-md-2 g-4">
        <?php
            if($this->view->requests != NULL) {
            foreach($this->view->requests as $key => $patient) {
                if($_SESSION['id_patient'] == $patient['id_patient']) {
        ?>
            <div class="col">
                <div class="card">
                    <div class="card-header">Dados da consulta</div>
                    <div class="card-body">
                        <h5 class="card-title"><?= "Paciente: " . $_SESSION['namepatient'] ?></h5>
                        <p class="card-text"><?= "Horário: " . date('d-m-Y', strtotime($patient['date'])) . " às " . date('H:i', strtotime($patient['date'])) ?></p>
                    </div>
                </div>
            </div>

        <?php                    
                }
            }}
        ?>
    </div>
</div>

<script>
    function Click(schedule) {
        var clinic = document.getElementById("Clinics").value;
        
        window.location.replace("/patient/schedule?id_medclinic=" + clinic + "&schedule=" + schedule);
    }
</script>