<h1>Fazer login</h1>

<?php
    if(isset($_GET)) {
        if(isset($_GET['registered']) && $_GET['registered'] == 'true') {
?>
            <div class="alert alert-success alert-dismissible fade show" role="alert">
                Paciente cadastrado com sucesso!
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
<?php
        }

        if(isset($_GET['login']) && $_GET['login'] == 'false') {
?>
            <div class="alert alert-warning alert-dismissible fade show" role="alert">
                Verifique se o email e / ou a senha estão corretos!
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
<?php
        }
    }
?>
<form action="/patient/tologin" method="post">
    <label for="">Email</label>
    <input type="email" name="email" required>
    <label for="">Senha</label>
    <input type="password" name="password" required>
    <button type="submit">Entrar</button>
    <a href="/patient/register">Cadastrar-se</a>
    <a href="/patient/recoverpass">Esqueci minha senha</a>
</form>