<div class="container">

    <h1>Cadastrar-se</h1>

    <?php
        if(isset($_GET)) {
            if(isset($_GET['registered']) && $_GET['registered'] == 'false') {
                echo "Paciente já cadastrado";
            }
        }
    ?>
    <form action="/patient/toregister" method="post">
        <label for="">Nome</label>
        <input type="text" name="name" required>
        <label for="">Email</label>
        <input type="email" name="email" required>
        <label for="">Telefone</label>
        <input type="tel" name="tel" required>
        <label for="">Endereço</label>
        <input type="text" name="address" required>
        <label for="">Senha</label>
        <input type="password" name="password" required>
        <button type="submit">Cadastrar-se</button>
        <a href="/patient/login">Entrar</a>
    </form>
</div>