<div class="container">
    <button type="button" onclick="javascript:history.go(-1)"  class="btn btn-secondary">Voltar</button>

    <h1>Atualizar secretária</h1>
    <?php
        if(isset($_GET)) {
            if(isset($_GET['update']) && $_GET['update'] == 'erro') {
    ?>
                <div class="alert alert-warning alert-dismissible fade show" role="alert">
                    Falha ao atualizar!
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
    <?php
            }
        }
    ?>
    <form action="/doctor/update/secretary" method="post">
        <input type="hidden" name="id_secretary" value="<?= $this->view->secretary[0]['id_secretary'] ?>">
        <div class="form-group">
            <label for="">Nome</label>
            <input type="text" name="name" class="form-control" value="<?= $this->view->secretary[0]['name'] ?>" required>
        </div>
        <div class="form-group">
            <label for="">Email</label>
            <input type="email" name="email" class="form-control" value="<?= $this->view->secretary[0]['email'] ?>" required>
        </div>
        <div class="form-group">
            <label for="">Telefone</label>
            <input type="tel" name="tel" class="form-control" value="<?= $this->view->secretary[0]['tel'] ?>" required>
        </div>
        <div class="form-group">
            <label for="">Senha</label>
            <input type="password" name="password" class="form-control" required>
        </div>
        <div class="form-group">
            <label for="">Responsável pela clínica</label>
            <select name="id_medclinic" class="form-control" id="">
                <?php foreach($this->view->clinics as $key => $clinic) { ?>
                <option value="<?= $clinic['id_medclinic'] ?>"><?= $clinic['name'] ?></option>
                <?php } ?>
            </select>
        </div>
        <div class="form-group">
            <input type="checkbox" name="is_super" class="form-control">
            <label for="">É uma super secretária</label>
        </div>
        <button type="submit" class="btn btn-primary">Atualizar</button>
    </form>
</div>