<div class="container">
    <button type="button" onclick="javascript:history.go(-1)" class="btn btn-secondary">Voltar</button>

    <h1>Editar dados da clínica</h1>

    <?php
        if(isset($_GET)) {
            if(isset($_GET['registered']) && $_GET['registered'] == 'true') {
    ?>
                <div class="alert alert-success alert-dismissible fade show" role="alert">
                    Cadastro feito com sucesso!
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
    <?php
            } else if(isset($_GET['registered']) && $_GET['registered'] == 'false') {
    ?>
                <div class="alert alert-warning alert-dismissible fade show" role="alert">
                    Falha ao cadastrar!
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
    <?php
            }
        }
    ?>
    <form action="/doctor/update/clinic" method="post">
        <input type="hidden" name="id_medclinic" value="<?= $this->view->clinic[0]['id_medclinic'] ?>">
        <div class="form-group">
            <label for="">Nome</label>
            <input type="text" name="name" class="form-control" value="<?= $this->view->clinic[0]['name'] ?>" required>
        </div>
        <div class="form-group">
            <label for="">Email</label>
            <input type="email" name="email" class="form-control" value="<?= $this->view->clinic[0]['email'] ?>" required>
        </div>
        <div class="form-group">
            <label for="">Telefone</label>
            <input type="tel" name="tel" class="form-control" value="<?= $this->view->clinic[0]['tel'] ?>" required>
        </div>
        <div class="form-group">
            <label for="">Endereço</label>
            <input type="tex" name="address" class="form-control" value="<?= $this->view->clinic[0]['address'] ?>" required>
        </div>
        <div class="form-group">
            <label for="">CNPJ</label>
            <input type="text" name="cnpj" class="form-control" value="<?= $this->view->clinic[0]['cnpj'] ?>" required>
        </div>
        <button type="submit" class="btn btn-primary">Atualizar</button>
    </form>
</div>