<div class="container">
    <button type="button" onclick="javascript:history.go(-1)">Voltar</button>
    <?php
        if(isset($_GET)) {
            if(isset($_GET['registered']) == 'true') {
                echo "Cadastro feito com sucesso!";
            } else if(isset($_GET['registered']) == 'false') {
                echo "Falha ao cadastrar";
            }
        }
    ?>

    <h1>Editar dados da clínica</h1>

    <form action="/doctor/update/clinic" method="post">
        <input type="hidden" name="id_medclinic" value="<?= $this->view->clinic[0]['id_medclinic'] ?>">
        <label for="">Nome</label>
        <input type="text" name="name" value="<?= $this->view->clinic[0]['name'] ?>" required>
        <label for="">Email</label>
        <input type="email" name="email" value="<?= $this->view->clinic[0]['email'] ?>" required>
        <label for="">Telefone</label>
        <input type="tel" name="tel" value="<?= $this->view->clinic[0]['tel'] ?>" required>
        <label for="">Endereço</label>
        <input type="tex" name="address" value="<?= $this->view->clinic[0]['address'] ?>" required>
        <label for="">CNPJ</label>
        <input type="text" name="cnpj" value="<?= $this->view->clinic[0]['cnpj'] ?>" required>
        <button type="submit">Atualizar</button>
    </form>
</div>