<div class="container">
    <button type="button" onclick="javascript:history.go(-1)">Voltar</button>

    <?php
        if(isset($_GET)) {
            if(isset($_GET['update']) == 'erro') {
                echo "Falha ao atualizar!";
            }
        }
    ?>

    <h1>Atualizar secretária</h1>

    <form action="/doctor/update/secretary" method="post">
        <input type="hidden" name="id_secretary" value="<?= $this->view->secretary[0]['id_secretary'] ?>">
        <label for="">Nome</label>
        <input type="text" name="name" value="<?= $this->view->secretary[0]['name'] ?>" required>
        <label for="">Email</label>
        <input type="email" name="email" value="<?= $this->view->secretary[0]['email'] ?>" required>
        <label for="">Telefone</label>
        <input type="tel" name="tel" value="<?= $this->view->secretary[0]['tel'] ?>" required>
        <label for="">Senha</label>
        <input type="password" name="password" required>
        <select name="id_medclinic" id="">
            <?php foreach($this->view->clinics as $key => $clinic) { ?>
            <option value="<?= $clinic['id_medclinic'] ?>"><?= $clinic['name'] ?></option>
            <?php } ?>
        </select>
        <input type="checkbox" name="is_super">
        <label for="">Responsável pela clínica</label>
        <label for="">É uma super secretária</label>
        <button type="submit">Atualizar</button>
    </form>
</div>