<div class="container">
    <a href="/doctor/logout" class="btn btn-primary">Sair</a>
    <h1>Doctor Home</h1>

    <nav>
        <a href="/doctor/secretary">Secretárias</a>
        <a href="/doctor/clinic">Clínicas</a>
    </nav>

    <label for="Clinics">Responsável pela clínica</label>
    <select name="id_medclinic" id="Clinics">
        <?php foreach($this->view->clinics as $key => $clinic) { ?>
            <option value="<?= $clinic['id_medclinic'] ?>"><?= $clinic['name'] ?></option>
        <?php } ?>
    </select>

    <?php include_once PARTIALS . "/calendar.phtml" ?>
    
</div>