<h1>Fazer login para doutor</h1>

<?php
    if($_GET) {
        if(isset($_GET['login']) && $_GET['login'] == 'false') {
?>
            <div class="alert alert-warning alert-dismissible fade show" role="alert">
                Verifique se o email e / ou a senha estão corretos!
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
<?php
        }
    }
?>
<form action="/doctor/tologin" method="post">
    <div class="form-group">
        <label for="">Email</label>
        <input type="email" name="email" class="form-control" required>
    </div>
    <div class="form-group">
        <label for="">Senha</label>
        <input type="password" name="password" class="form-control" required>
    </div>
    <button type="submit" class="btn btn-primary">Entrar</button>
</form>