<div class="container">
    <button type="button" onclick="javascript:history.go(-1)">Voltar</button>
    <?php
        if(isset($_GET)) {
            if(isset($_GET['registered']) == 'true') {
                echo "Cadastro feito com sucesso!";
            } else if(isset($_GET['registered']) == 'false') {
                echo "Falha ao cadastrar";
            }
        }
    ?>

    <h1>Cadastro de clínicas</h1>

    <form action="/doctor/register/clinic" method="post">
        <label for="">Nome</label>
        <input type="text" name="name" required>
        <label for="">Email</label>
        <input type="email" name="email" required>
        <label for="">Telefone</label>
        <input type="tel" name="tel" required>
        <label for="">Endereço</label>
        <input type="tex" name="address" required>
        <label for="">CNPJ</label>
        <input type="text" name="cnpj" required>
        <button type="submit">Cadastrar</button>
    </form>

    <hr>
    <h1>Controle de clínicas</h1>

        
    <table class="table table-striped">
        <thead>
            <tr>
            <th scope="col">Id</th>
            <th scope="col">Clínica</th>
            <th scope="col">CNPJ</th>
            <th scope="col">Ações</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach($this->view->clinics as $key => $clinic) { ?>
            <tr>
            <th scope="row"><?= $clinic['id_medclinic'] ?></th>
            <td><?= $clinic['name'] ?></td>
            <td><?= $clinic['cnpj'] ?></td>
            <td>
                <a href="/doctor/editclinic/<?= $clinic['id_medclinic'] ?>">Editar</a>
            </td>
            </tr>
            <?php } ?>
        </tbody>
    </table>
</div>