<div class="container">
    <button type="button" onclick="javascript:history.go(-1)" class="btn btn-secondary">Voltar</button>

    <h1>Cadastro de clínicas</h1>

    <?php
        if(isset($_GET)){
            if(isset($_GET['registered']) && $_GET['registered']== 'true') {
    ?>
                <div class="alert alert-success alert-dismissible fade show" role="alert">
                    Cadastro feito com sucesso!
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
    <?php
            }
            if(isset($_GET['registered']) && $_GET['registered']== 'false') {
    ?>
                <div class="alert alert-warning alert-dismissible fade show" role="alert">
                    Falha ao cadastrar!
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
    <?php
            }
        }
    ?>
    <form action="/doctor/register/clinic" method="post">
        <div class="form-group">
            <label for="">Nome</label>
            <input type="text" class="form-control" name="name" required>
        </div>
        <div class="form-group">
            <label for="">Email</label>
            <input type="email" class="form-control" name="email" required>
        </div>
        <div class="form-group">
            <label for="">Telefone</label>
            <input type="tel" class="form-control" name="tel" required>
        </div>
        <div class="form-group">
            <label for="">Endereço</label>
            <input type="tex" class="form-control" name="address" required>
        </div>
        <div class="form-group">
            <label for="">CNPJ</label>
            <input type="text" class="form-control" name="cnpj" required>
        </div>
        <button type="submit" class="btn btn-primary">Cadastrar</button>
    </form>

    <hr>
    <h1>Controle de clínicas</h1>

        
    <table class="table table-striped">
        <thead>
            <tr>
            <th scope="col">Id</th>
            <th scope="col">Clínica</th>
            <th scope="col">CNPJ</th>
            <th scope="col">Ações</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach($this->view->clinics as $key => $clinic) { ?>
            <tr>
            <th scope="row"><?= $clinic['id_medclinic'] ?></th>
            <td><?= $clinic['name'] ?></td>
            <td><?= $clinic['cnpj'] ?></td>
            <td>
                <div class="btn-group" role="group" aria-label="Basic example">
                    <a href="/doctor/editclinic/<?= $clinic['id_medclinic'] ?>" class="btn btn-success">Editar</a>
                    <button class="btn btn-danger" onclick="confirmDelete()">Excluir</button>
                </div>
            </td>
            </tr>
            <?php } ?>
        </tbody>
    </table>
</div>

<script>
    function confirmDelete() {
        var decision = confirm("Deseja realmente deletar?");
        if(decision) {
            window.location.assign("/doctor/delete/clinic/<?= $clinic['id_medclinic'] ?>");
        }
    }
</script>