<div class="container">

    <button type="button" onclick="javascript:history.go(-1)" class="btn btn-secondary">Voltar</button>
    <?php
        if(isset($_GET)) {
            if(isset($_GET['registered']) == 'true') {
                echo "Cadastro feito com sucesso!";
            } else if(isset($_GET['registered']) == 'false') {
                echo "Falha ao cadastrar";
            }
        }
    ?>

    <h1>Cadastro de secretárias</h1>

    <form action="/doctor/register/secretary" method="post">
        <div class="form-group">
            <label for="">Nome</label>
            <input type="text" class="form-control" name="name" required>
        </div>
        <div class="form-group">
            <label for="">Email</label>
            <input type="email" class="form-control" name="email" required>
        </div>
        <div class="form-group">
            <label for="">Telefone</label>
            <input type="tel" class="form-control" name="tel" required>
        </div>
        <div class="form-group">
            <label for="">Senha</label>
            <input type="password" class="form-control" name="password" required>
        </div>
        <div class="form-group">
            <label for="Clinics">Responsável pela clínica</label>
            <select name="id_medclinic" class="form-control" id="Clinics">
                <?php foreach($this->view->clinics as $key => $clinic) { ?>
                <option value="<?= $clinic['id_medclinic'] ?>"><?= $clinic['name'] ?></option>
                <?php } ?>
            </select>
        </div>
        <div class="form-check">
            <input type="checkbox" class="form-check-input" name="is_super">
            <label for="">É uma super secretária</label>
        </div>
        <button type="submit" class="btn btn-primary">Cadastrar</button>
    </form>

    <hr>
    <h1>Controle de Secretárias</h1>

        
    <table class="table table-striped">
        <thead>
            <tr>
            <th scope="col">Id</th>
            <th scope="col">Secretaria</th>
            <th scope="col">Clínica</th>
            <th scope="col">Ações</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach($this->view->secretaries as $key => $secretary) { ?>
            <tr>
            <th scope="row"><?= $secretary['id_secretary'] ?></th>
            <td>
                <?php
                    if($secretary['is_super'] != NULL) {
                        echo $secretary['name'] . " - (Super)";
                    } else {
                        echo $secretary['name'];
                    }
                ?>    
            </td>

            <?php foreach($this->view->clinics as $key => $clinic) { 
                if($secretary['id_medclinic'] == $clinic['id_medclinic']) {   
            ?>
                <td><?= $clinic['name'] ?></td>
            <?php }} ?>
            
            <td>
                <div class="btn-group" role="group" aria-label="Basic example">
                    <a href="/doctor/editsecretary/<?= $secretary['id_secretary'] ?>" class="btn btn-success">Editar</a>
                    <a href="" class="btn btn-danger">Excluir</a>
                </div>
            </td>
            </tr>
            <?php } ?>
        </tbody>
    </table>
</div>