<div class="container">

    <button type="button" onclick="javascript:history.go(-1)">Voltar</button>
    <?php
        if(isset($_GET)) {
            if(isset($_GET['registered']) == 'true') {
                echo "Cadastro feito com sucesso!";
            } else if(isset($_GET['registered']) == 'false') {
                echo "Falha ao cadastrar";
            }
        }
    ?>

    <h1>Cadastro de secretárias</h1>

    <form action="/doctor/register/secretary" method="post">
        <label for="">Nome</label>
        <input type="text" name="name" required>
        <label for="">Email</label>
        <input type="email" name="email" required>
        <label for="">Telefone</label>
        <input type="tel" name="tel" required>
        <label for="">Senha</label>
        <input type="password" name="password" required>
        <select name="id_medclinic" id="">
            <?php foreach($this->view->clinics as $key => $clinic) { ?>
            <option value="<?= $clinic['id_medclinic'] ?>"><?= $clinic['name'] ?></option>
            <?php } ?>
        </select>
        <input type="checkbox" name="is_super">
        <label for="">Responsável pela clínica</label>
        <label for="">É uma super secretária</label>
        <button type="submit">Cadastrar</button>
    </form>

    <hr>
    <h1>Controle de Secretárias</h1>

        
    <table class="table table-striped">
        <thead>
            <tr>
            <th scope="col">Id</th>
            <th scope="col">Secretaria</th>
            <th scope="col">Clínica</th>
            <th scope="col">Ações</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach($this->view->secretaries as $key => $secretary) { ?>
            <tr>
            <th scope="row"><?= $secretary['id_secretary'] ?></th>
            <td>
                <?php
                    if($secretary['is_super'] != NULL) {
                        echo $secretary['name'] . " - (Super)";
                    } else {
                        echo $secretary['name'];
                    }
                ?>    
            </td>

            <?php foreach($this->view->clinics as $key => $clinic) { 
                if($secretary['id_medclinic'] == $clinic['id_medclinic']) {   
            ?>
                <td><?= $clinic['name'] ?></td>
            <?php }} ?>
            
            <td>
                <a href="/doctor/editsecretary/<?= $secretary['id_secretary'] ?>">Editar</a>
            </td>
            </tr>
            <?php } ?>
        </tbody>
    </table>
</div>